

#
# User configuration sourced by interactive shells
#

# Change default zim location
export ZIM_HOME=${ZDOTDIR:-${HOME}}/.zim

# Start zim
[[ -s ${ZIM_HOME}/init.zsh ]] && source ${ZIM_HOME}/init.zsh

# CUDA stuff
export PATH=/usr/local/cuda-9.0/bin${PATH:+:${PATH}}
export LD_LIBRARY_PATH=/usr/local/cuda-9.0/lib64${LD_LIBRARY_PATH:+:${LD_LIBRARY_PATH}}


# ROS Stuff
#source /opt/ros/kinetic/setup.zsh
#source ~/zed_ws/devel/setup.zsh
#export ROS_PACKAGE_PATH=${ROS_PACKAGE_PATH}:~/orbslam/ORB_SLAM2/Examples/ROS

# source aliases
source_alias_failed() {echo "Sourcing aliases failed. Softlinking Ubuntu-install-scripts might have failed. Please run 1 - Set Up Basic Environment.sh again"}
source ~/Ubuntu-install-scripts/config_files/aliases.sh || source_alias_failed
